### ISSUE TITLE
400 Request Exception when trying to generate commit

### ISSUE THREAD

**Issue by RONNCC** [guanguans/ai-commit#110]
**Describe the bug**

```
  [Illuminate\Http\Client\RequestException (400)]
  HTTP request returned status code 400
```

**To Reproduce**
1. Configure ai-commit
2. Run `ai-commit commit -v`
3. See error

**Expected behavior**
I expected the function to work similar to the demo

**Screenshots**
<img width="1035" alt="image" src="https://github.com/guanguans/ai-commit/assets/1313566/ef111ac5-9228-4fa3-9bed-000cd14f7061">

**Additional context**

**Comment by RONNCC** [comment]
Would be helpful to see the request it's submitting to the OpenAI API here to help debug the bad request

**Comment by guanguans** [comment]
@RONNCC 

Try to configure request parameters:

```shell
./ai-commit config set generators.openai.parameters.stream false
./ai-commit config set generators.openai_chat.parameters.stream false
```

Or update to the latest:

```shell
ai-commit self-update
```
