### ISSUE TITLE
增加一个配置，让ai-commit忽略部分文件

### ISSUE THREAD

**Issue by BaoziCDR** [guanguans/ai-commit#112]
**Is your feature request related to a problem? Please describe.**
我使用protobuf生成一些文件，提交代码的时候ai-commit会去分析这些文件，这样耗费我大量的token，而且3.5模型会因为超大上下文而无法正常工作。

**Describe the solution you'd like**
能不能增加一个配置，让ai-commit忽略部分文件，像.gitignore那样，以xx开头文件不作为prompt发送

**Describe alternatives you've considered**
我尝试过在prompt让AI不分析生成式文件，但似乎不起作用

非常感谢作者让我们用上这么方便的工具（造福想不出commit词的打工人）

**Comment by guanguans** [comment]
@BaoziCDR

应该可以通过 `diff_options` 配置来实现，新增加 `":!xxx.*"` 试试看。


```json
{
    "commit_options": [
        "--edit"
    ],
    "diff_options": [
        ":!*-lock.json",
        ":!*.lock",
        ":!*.sum"
    ],
    "http_options": {
        "verify": false,
        "connect_timeout": 30,
        "timeout": 120
    },
    ...
}
```

**Comment by BaoziCDR** [comment]
@guanguans 

谢谢！添加这个配置确实有用~
