### ISSUE TITLE
1.10.1 版本的commit message 格式有问题

### ISSUE THREAD

**Issue by xuwei152** [guanguans/ai-commit#115]
我升级到1.10.1 版本之后 commit message 的格式变成下图了
![Clip_2024-03-20_11-49-16](https://github.com/guanguans/ai-commit/assets/51861161/30f19e5b-b29a-414d-bad5-51d7c82abb4f)
![Clip_2024-03-20_11-50-27](https://github.com/guanguans/ai-commit/assets/51861161/de6999c5-5c4a-4f7e-b485-eb79a4407915)

id 1 也到commit message里面了

1.8.2 版本没问题
![Clip_2024-03-20_11-52-35](https://github.com/guanguans/ai-commit/assets/51861161/b9276b67-c1d1-467a-98ec-96a2a3514b89)
![Clip_2024-03-20_11-54-15](https://github.com/guanguans/ai-commit/assets/51861161/377b19f2-5a74-4320-a0d5-1e2248cc7788)

**Comment by guanguans** [comment]
@xuwei152 

重置提示语试试：

```shell
./ai-commit config reset prompts.conventional
```

**Comment by xuwei152** [comment]
可以了，谢谢
