### ISSUE TITLE
Specify the type of commit or input key words

### ISSUE THREAD

**Issue by xuwei152** [guanguans/ai-commit#128]
**Is your feature request related to a problem? Please describe.**

Many of the AI's commit messages are incorrect, even for the type. 

```text
<type>[optional scope]: <description>

[optional body]

[optional footer(s)]
```

**Describe the solution you'd like**

Is it possible to specify the type of commit message or key words to help Ai to generate the commit message more accurately?

**Comment by guanguans** [comment]
@xuwei152 You can try to configure a customized prompt.

`/your home directory/.ai-commit/.ai-commit.json` or `current working directory/.ai-commit.json`

```json
{
    ...
    "prompt": "custom",
    "prompts": {
        "conventional": "Here are some best practices...",
        "custom": "..."
    }
}
```

**Comment by xuwei152** [comment]
I mean feed the "type" to the AI in the prompt like the "no" to correct the generated message.

For example, the commit message shown below has a type of "refactor" but it is a type of "chore", actually. I hope to input the type "chore" to tell the AI to generate a message with a type of "chore", instead of typing "no" again and again and getting incorrect messages. Something likes chatting with the Ai bot to correct the answer. I don't think this can be achieved by configuring ".ai-commit.json".

![Clip_2024-05-08_13-33-04](https://github.com/guanguans/ai-commit/assets/51861161/f72c33ad-b4b2-4fc5-aec2-e066ab1ff676)

There may be an easier way. You can add an option of "--commit-type" like [insulineru/ai-commit](https://github.com/insulineru/ai-commit).


![Clip_2024-05-08_14-06-24](https://github.com/guanguans/ai-commit/assets/51861161/876cddf3-52cb-4125-9346-d16266072d48)
