### ISSUE TITLE
希望支持GPT4o

### ISSUE THREAD

**Issue by BaoziCDR** [guanguans/ai-commit#138]
**Is your feature request related to a problem? Please describe.**
似乎目前不支持 gpt4o，后续有支持计划嘛

**Describe the solution you'd like**
gpt4o模型价格比gp4便宜，而且生成速度更快，希望能够支持

<img width="315" alt="image" src="https://github.com/guanguans/ai-commit/assets/44897251/624746be-17b3-4cce-bc2f-097d45746292">

**Comment by guanguans** [comment]
@BaoziCDR 更新到最新版本再试试。

**Comment by BaoziCDR** [comment]
@guanguans 好像还有个bug，使用self-update不能更新到最新版本
<img width="755" alt="image" src="https://github.com/guanguans/ai-commit/assets/44897251/873937c8-9d22-40e5-bba7-cbe50c3f4d55">
我是使用Composer 安装的

**Comment by guanguans** [comment]
@BaoziCDR 对的是差一个版本。
