### ISSUE TITLE
Option to get a summary (commit message) back, without making a commit, for any diff

### ISSUE THREAD

**Issue by sunnysideup** [guanguans/ai-commit#167]
**Is your feature request related to a problem? Please describe.**
No, just having a look.

**Describe the solution you'd like**
I was wondering if I could simply use this module to get a git commit message back, rather than doing the actual commit.  Basically I want to provide a diff (or two commit hashes) and then have ai-commit summarise those. 

**Describe alternatives you've considered**

Also looked at: https://github.com/KanHarI/gpt-commit-summarizer. But prefer your module as it is PHP based. 

**Additional context**

Great work!!!!!!!!

**Comment by guanguans** [comment]
@sunnysideup 

Sorry. This feature is not currently supported.

The new --diff and --dry-run options need to be added to support it.

**Comment by guanguans** [comment]
@sunnysideup

I have added `--diff` and `--dry-run` options. Please try to update to the latest version.
