### ISSUE TITLE
cURL error 60: SSL certificate problem

### ISSUE THREAD

**Issue by christopherpross** [guanguans/ai-commit#7]
**Describe the bug**
I can not use the command 'ai-commit commit'. It gives me an error about a ssl certificate problem.

**To Reproduce**
1. Open PowerShell under Windows (current version)
2. Go into the folder with the git-repo to use with ai-commit
3. make sure that your apikey is correct
4. Enter the command 'ai-commit commit'
5. see the following output:
`1. Generating commit messages: failed

In CurlFactory.php line 211:

  cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/
  libcurl-errors.html) for https://api.openai.com/v1/completions`

**Expected behavior**
The error should not accoure and the commit should have been generated.

**Additional context**

* OS: Windows 11 
* Shell: PowerShell Core 7.2
* php version: `PHP 7.4.33 (cli) (built: Nov  2 2022 16:00:55) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
`
* ai-commit version: 1.2.6

**Comment by guanguans** [comment]
@christopherpross 

Try to close the certificate verification.

```
# Can find the configuration file.
./ai-commit config list
```

<img width="664" alt="image" src="https://user-images.githubusercontent.com/22309277/222033567-f019872a-a69f-4848-892e-a19a1664f86a.png">



<img width="840" alt="image" src="https://user-images.githubusercontent.com/22309277/222034796-38988721-60e6-46c0-87b1-10f05af7a521.png">

**Comment by christopherpross** [comment]
@guanguans  
thank you for your answer. I didn't know that this option exist. Maybe mention that in the readme?

**Comment by guanguans** [comment]
@christopherpross https://docs.guzzlephp.org/en/latest/request-options.html
There are many HTTP client options. General use the default on it, so there is no added description, I will add it later.
